---
- name: Check if redis is installed
  sudo: no
  ignore_errors: yes
  command: test -e /usr/local/systemd/system/redis.service
  register: is_redis_installed

- name: Install redis with yum
  yum: name={{ item }} state=latest
  with_items:
    - redis
  when: is_redis_installed | failed

- name: redis should be started
  service: name=redis enabled=yes state=started
