---
- name: nginx | Add yum-repo
  yum_repository:
    name: nginx
    description: "nginx yum-repo"
    baseurl: http://nginx.org/packages/centos/7/$basearch/
    gpgcheck: no
    enabled: yes

- name: nginx | Yum install
  yum:
    name: nginx
    enablerepo: nginx
    state: present


- name: nginx | start httpd service automaticaly
  service:
    name: nginx
    state: started
    enabled: yes
