---
- name: Include vars
  include_vars:
    file: ../files/files.yml

- name: Replace file to templates/xx
  ignore_errors: yes
  template:
    src: "{{ item.replacefile }}"
    dest: "{{ item.targetfile }}"
    backup: yes
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ files.replace_file }}"

- name: Replace file to directories/xx
  ignore_errors: yes
  copy:
    backup: yes
    src: "{{ item.replacedirectory }}"
    dest: "{{ item.targetdirectory }}"
  with_items: "{{ files.replace_directory }}"
