- name: Apacheとヘッダファイルのインストール
  become: yes
  yum:
    name='httpd,httpd-devel'
    state=latest

- name: Create apache group
  group:
    name: apache
    state: present

- name: Create apache user
  user:
    name: apache
    shell: /sbin/nologin
    group: apache
    createhome: yes
    state: present

- name: chown /var/www/html
  file:
    path: /var/www/html
    state: directory
    owner: apache
    group: apache
    recurse: yes

- name: start httpd service automaticaly
  service: name=httpd state=started enabled=yes
