---
# - name: Exec common role
#   hosts: all
#   sudo: yes
#   vars:
#     projectname: ansiblate
#   vars_files:
#     - secrets.yml
#   roles:
#     - common
#     - ntp
#     - { role: mackerel, when: "env == 'production'" }

- name: Exec common role
  hosts: mate
  sudo: yes
  vars:
    project_name: mate
    appuser: "{{ project_name }}"
    appgroup: "{{ project_name }}"
    appuser_root: '/home/"{{ project_name }}"'
    project_root: '/home/"{{ project_name }}"/"{{ project_name }}"'
  roles:
    - act-reachability
