---
# - name: Exec common role
#   hosts: all
#   sudo: yes
#   vars:
#     projectname: ansiblate
#   vars_files:
#     - secrets.yml
#   roles:
#     - common
#     - ntp
#     - { role: mackerel, when: "env == 'production'" }

- name: Exec common role
  hosts: validater
  sudo: yes
  vars:
    project_name: varidater
    appuser: "{{ project_name }}"
    appgroup: "wheel"
    appuser_root: '/home/"{{ project_name }}"'
    project_root: '/home/"{{ project_name }}"/"{{ project_name }}"'
    app_root: '/home/"{{ project_name }}"/"{{ project_name }}"/app'
  roles:
    - selenium-chrome

# - name: Exec install python and struct django in virtualenv project.
#   hosts: python
#   sudo: yes
#   vars:
#     project_name: django-project
#     appuser: "{{ project_name }}"
#     appgroup: "{{ project_name }}"
#     appuser_root: '/home/"{{ project_name }}"'
#     project_root: '/home/"{{ project_name }}"/"{{ project_name }}"'
#     app_root: '/home/"{{ project_name }}"/"{{ project_name }}"/app'
#   roles:
#     - python
#     - django

# - name: Setup GUI enviroment
#   hosts: xwindows
#   sudo: yes
#   roles:
#     - xwindows
#     - firefox
#
# - name: Setup web server with apache
#   hosts: apache
#   sudo: yes
#   roles:
#     - apache
#    - firewalld
#
# - name: Setup proxy server
#  hosts: proxy
#  sudo: yes
#  roles:
#    - nginx
#    - firewalld
#
# - name: Setup development enviroment with ruby
#   hosts: ruby
#   sudo: yes
#   roles:
#     - git
#     - ruby
#     - postgresql
#
# - name: Setup development enviroment with java
#   hosts: java
#   sudo: yes
#   roles:
#     - git
#     - java
#     - tomcat
#     - postgresql
