---
- name: Reload bash_profile
  shell: source /home/{{ appuser }}/.bash_profile

- name: Check if project_folder is installed
  sudo: no
  ignore_errors: yes
  command: test -e /home/{{ appuser }}/{{ project_name }}
  register: is_venv_structed

- name: Activate ProjectVirtualEnviroment
  shell: /usr/local/bin/python -m venv /home/{{ appuser }}/{{ project_name }}
  when: is_venv_structed | failed

- name: chown project_directory
  file:
    path: /home/{{ appuser }}/{{ project_name }}
    state: directory
    owner: "{{ appuser }}"
    group: wheel
    recurse: yes
  when: is_venv_structed | failed

# 仮想環境内のpipを使えば仮想環境内のlibにインストールしてくれるらしい
- name: Install tensorflow into virtualenv with pip
  pip:
    name: "{{ item }}"
    executable: /home/{{ appuser }}/{{ project_name }}/bin/pip
    state: present
  with_items:
    - tensorflow
