---
- name: Include vars
  include_vars:
    file: vars/all.yml

- name: Remove default git
  yum: name=git state=absent

- name: Install dependent packages of git
  yum: name={{ item }} enablerepo=epel state=latest
  with_items:
    - curl-devel
    - expat-devel
    - gettext-devel
    - openssl-devel
    - zlib-devel
    - gcc
    - perl-ExtUtils-MakeMaker

- name: Check if git is installed
  sudo: no
  ignore_errors: yes
  command: which git
  register: is_git_installed

- name: Make directories
  file: path={{ appuser_root }}/src state=directory owner={{ appuser }} group={{ appgroup }}
  when: is_git_installed | failed

- name: Download git.tar.gz
  get_url: url=https://www.kernel.org/pub/software/scm/git/{{ git_version }}.tar.gz dest={{ appuser_root }}/src/
  when: is_git_installed | failed

- name: Unpacking git.tar.gz
  unarchive: src={{ appuser_root }}/src/{{ git_version }}.tar.gz dest={{ appuser_root }}/src copy=no
  when: is_git_installed | failed

- name: make all
  sudo: yes
  make:
    chdir: "{{ appuser_root }}/src/{{ git_version }}"
    target: all
    params:
      prefix: /usr/local
  when: is_git_installed | failed

- name: make install
  sudo: yes
  make:
    chdir: "{{ appuser_root }}/src/{{ git_version }}"
    target: install
    params:
      prefix: /usr/local
  when: is_git_installed | failed
