- name: Remove default git
  yum: name=git state=absent

- name: Install dependent packages of git
  yum: name={{ item }} enablerepo=epel state=latest
  with_items:
    - curl-devel
    - expat-devel
    - openssl-devel
    - zlib-devel
    - perl-ExtUtils-MakeMaker

- name: Check if git is installed
  sudo: no
  ignore_errors: yes
  command: which git
  register: is_git_installed

- name: Download git.tar.gz
  get_url: url=https://www.kernel.org/pub/software/scm/git/{{ git_version }}.tar.gz dest={{ project_root }}/src
  when: is_git_installed | failed

- name: Unpacking git.tar.gz
  unarchive: src={{ project_root }}/src/{{ git_version }}.tar.gz dest={{ project_root }}/src copy=no
  when: is_git_installed | failed

- name: Install git
  command: "{{ item }} chdir={{ project_root }}/src/{{ git_version }}"
  with_items:
    - make prefix=/usr/local all
    - make prefix=/usr/local install
  when: is_git_installed | failed
