---
- name: Download Gatling
  sudo: yes
  get_url: url={{ gatling_url }} dest={{ install_dir }}

- name: Extract Gatling
  sudo: yes
  unarchive: copy=no src={{ install_dir }}/{{ gatling_archive }}.zip dest={{ install_dir }}

- name: Remove downloaded archive
  sudo: yes
  shell: "rm -f {{ install_dir }}/{{ gatling_archive }}.zip"

- name: Create symboliclink for gatling.sh and recorder.sh
  lineinfile:
    path: /etc/profile
    insertafter: EOF
    line: 'export GATLING_HOME={{ install_dir }}/{{ gatling_dir }}/'

- name: Reload bash_profile
  sudo: yes
  shell: source /etc/profile

- name: Create symboliclink for gatling.sh and recorder.sh
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items:
    - { src: '{{ install_dir }}/{{ gatling_dir }}/bin/gatling.sh', dest: '/usr/local/bin/gatling' }
    - { src: '{{ install_dir }}/{{ gatling_dir }}/bin/recorder.sh'   , dest: '/usr/local/bin/recorder' }
