production:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: true
      address: "smtp.gmail.com"
      port: 587
      domain: "smtp.gmail.com"
      authentication: :plain
      user_name: "{{ redmine_mail_address }}"
      password: "{{ redmine_mail_pass }}"

  rmagick_font_path: {{ redmine_font_path }}
