---
- name: Docker | Install Common Items for Docker
  become: yes
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: latest

- name: Docker | check docker-ce.repo
  stat: path=/etc/yum.repos.d/docker-ce.repo
  register: docker_ce

- name: add docker repo
  shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
  args:
    chdir: "/etc/yum.repos.d"
    creates: docker-ce.repo
  when: docker_ce.stat.exists == false

- name: Docker | Install Docker ce
  become: yes
  yum:
    name: docker-ce
    state: present

- name: Docker | Docker should be started
  service: name=docker enabled=yes state=started

- name: Docker-Compose | Check if docker-compose is installed
  sudo: no
  ignore_errors: yes
  command: test -e /usr/local/bin/docker-compose
  register: is_docker_compose_installed

- name: Docker-Compose | Install auxiliary packages for Docker with yum
  shell: "curl -L \"https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/local/bin/docker-compose"
  when: is_docker_compose_installed | failed

- name: Docker-Compose | Give exec permission
  file:
    path: /usr/local/bin/docker-compose
    mode: "u+x,g+x,o+x"


# OS: Ubuntu
# - name: Docker | Prerequisites
#   sudo: yes
#   shell: "{{item}}"
#   with_items:
#     - "apt-get update"
#     - "apt-get install -y apt-transport-https"
#
# - name: Docker | Add repo to APT sources
#   sudo: yes
#   shell: "echo deb https://apt.dockerproject.org/repo ubuntu-trusty main > /etc/apt/sources.list.d/docker.list"
#
# - name: Docker | Import the repo key
#   sudo: yes
#   shell: "apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D"
#
# - name: Docker | Install Docker 17.03.0~ce
#   sudo: yes
#   shell: "{{item}}"
#   with_items:
#     - "apt-get update"
#     - "apt-get install -y docker-engine=17.03.0~ce-0~ubuntu-trusty"
