---
- name: Include vars
  include_vars:
    file: vars/all.yml

- name: Remove default ruby
  yum: name=ruby state=absent

- name: Install dependent packages of ruby
  yum: name={{ item }} enablerepo=epel state=latest
  with_items:
    - zlib-devel
    - openssl-devel
    - libffi-devel

- name: Check if ruby is installed
  sudo: no
  ignore_errors: yes
  command: which ruby
  register: is_ruby_installed

- name: Download ruby
  get_url:
    url: "{{ ruby_path }}"
    dest: "{{ appuser_root }}/src/"
  when: is_ruby_installed | failed

- name: Unpacking ruby.tar.gz
  unarchive: src={{ appuser_root }}/src/{{ ruby_archaive }} dest={{ appuser_root }}/src copy=no
  when: is_ruby_installed | failed

- name: Install ruby
  command: "{{ item }} chdir={{ appuser_root }}/src/{{ ruby_version }}"
  with_items:
    - ./configure --prefix=/usr/local
    - make
    - make install
  when: is_ruby_installed | failed

- name: Update rubygems
  command: /usr/local/bin/gem update --system

- name: Install bundler by rubygems
  gem:
    name=bundler
    version=1.10.2
    executable=/usr/local/bin/gem
    user_install=False
